# Site settings
# These are used to personalize your new site.
title: Cody Scholl # your name here
logo: "/images/Snapchat-2048975334.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2020)
  <br /><br />
  <a href="https://github.com/codyscholl/codyscholl.github.io/blob/master/pdf/ActualResumePDF.pdf">View My Resume</a>
  <br /><br />
repository: "codyscholl/codyscholl.github.io"
github_username:  codyscholl # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

